server:
  port: 8080  # API Gateway should use a different port (not 8761)

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable automatic route creation
          lower-case-service-id: true
        routes:
          - id: alert-service
            uri: lb://alert-service
            predicates:
              - Path=/alert-service/**
            filters:
              - StripPrefix=1

          - id: recommendation-service
            uri: lb://recommendation-service
            predicates:
              - Path=/recommendation-service/**
            filters:
              - StripPrefix=1

          - id: weather-service
            uri: lb://weather-service
            predicates:
              - Path=/weather-service/**
            filters:
              - StripPrefix=1

          - id: parcel-service
            uri: lb://parcel-service
            predicates:
              - Path=/parcel-service/**
            filters:
              - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"